on:
  workflow_dispatch:
  push:
    branches:
      - 'release/v2.4'

jobs:
  archi_report:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    name: Deploy Archi report HTML to GitHub Pages
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set Archi preferences
        run: |
          mkdir -p ./settings
          echo "eclipse.preferences.version=1" > "./settings/com.archimatetool.editor.prefs"
          echo "lineJumps=false" >> "./settings/com.archimatetool.editor.prefs"
      - name: Deploy Archi report
        run: |
          docker run --rm \
            -v "${{ github.workspace }}:/github/workspace" \
            -v "${{ github.workspace }}/settings:/root/.archi/.metadata/.plugins/org.eclipse.core.runtime/.settings" \
            -e GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
            -e ARCHI_HTML_REPORT_ENABLED="true" \
            -e ARCHI_JASPER_REPORT_ENABLED="true" \
            -e ARCHI_JASPER_REPORT_FORMATS="PDF,DOCX" \
            -e ARCHI_CSV_REPORT_ENABLED="true" \
            -e ARCHI_EXPORT_MODEL_ENABLED="true" \
            ghcr.io/woozymasta/archimate-ci-image:5.7.0-1.0.6
