on:
  workflow_dispatch:
  push:
    branches:
      - 'release/v2.4'

jobs:
  archi_report:
    permissions:
      contents: write
      pages: write
    runs-on: ubuntu-latest
    name: Deploy Archi report HTML to GitHub Pages
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set Archi preferences
        run: |
          mkdir -p "${{ runner.temp }}/_github_home/.archi/.metadata/.plugins/org.eclipse.core.runtime/.settings"
          echo "eclipse.preferences.version=1" > "${{ runner.temp }}/_github_home/.archi/.metadata/.plugins/org.eclipse.core.runtime/.settings/com.archimatetool.editor.prefs"
          echo "lineJumps=false" >> "${{ runner.temp }}/_github_home/.archi/.metadata/.plugins/org.eclipse.core.runtime/.settings/com.archimatetool.editor.prefs"
      - name: Deploy Archi report
        id: archi
        uses: WoozyMasta/archimate-ci-image@5.7.0-1.0.6
        with:
          archiHtmlReportEnabled: true
          archiJasperReportEnabled: true
          archiJasperReportFormats: PDF,DOCX
          archiCsvReportEnabled: true
          archiExportModelEnabled: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}
